FROM registry.redhat.io/ubi8/dotnet-50

USER 0

COPY app /opt/app-root/src
RUN chown -R 1001:0 /opt/app-root/src

RUN dotnet --info

USER 1001
RUN dotnet publish -c Release -o /opt/app-root/app
CMD dotnet /opt/app-root/app/app.dll
